### ISSUE TITLE
UnauthorisedException "Bad credentials" despite the same request working in a browser

### ISSUE THREAD

**Issue by TheBoxyBear** [in2bits/IronGitHub#23]
Trying to get a gist and cloned the repo and manually added the project to my solution instead of the nuget package so I could debug it.

Calling GistsApi.Get() and GitHubApiBase.CreateRequest() generates a URI that when viewed in a browser returns JSON with all the info about the gist. However, GitHubBase.Complete() which returns Task<ApiResponse> enter the catch block on await request.GetResponseAsync().ConfigureAwait(false); with the exception containing error code 401.

**Comment by TheBoxyBear** [comment]
Changing the user agent to match my browser's still causes the exception to be thrown.

**Comment by johnduhart** [comment]
@TheBoxyBear This library hasn't been updated in 5+ years, it's likely not to work with whatever latest API changes exist. Have you tried using [octokit](https://github.com/octokit/octokit.net)? This library predates an official .NET client.

**Comment by TheBoxyBear** [comment]
Well I found the issue regardless. For some reason the API sends 401 if you provide a token when the request doesn't need a token. IronGitHub provides the token in the headers regardless.

**Comment by TheBoxyBear** [comment]
And no, never heard of Octokit. Was just searching in NuGet and it never came up in the results. I will check it out.
